### ISSUE TITLE
Add apt repo for ubuntu22 in bigtop-ambari-mpack

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/bigtop#22]
## Description
By default bigtop-ambari-mpack support only centos7 stack deploy. There are requared to add ubuntu22 OS deployment.

## Tasks
- [x] Add ubuntu22 OS apt repo
- [x] Update CI/CD build job on Jenkins
- [x] Build bigtop-ambari-mpack and create new apt repo using Jenkins jobs.
