### ISSUE TITLE
Change bigtop-ambari-mpack to deploy AMS from ODP stack properly

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/bigtop#26]
# Tasks
- [x] Change BGTP Ambari MPack to fix AMS Collector startup
- [x] Fix Grafana dashboards to support updated Grafana version
- [x] Improve python scripts and configuration files
