### ISSUE TITLE
Build custom assembly

### ISSUE THREAD

**Issue by Nazarii-Melnyk** [rework-space-com/bigtop#5]
## Requirements
- [x] #3 

## Tasks 
- [x] Research how to build specific artifact versions
- [x] Build artifacts with versions that was chosen
- [x] Create apt repository for Ubuntu 22.04
